name: 'Push Environment'
description: 'Bumps application version in the -environment repository'
author: 'Ignitia'

inputs:
  application:
    description: 'The name of the application to update'
    required: true
  version:
    description: 'The version to set'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Push to environment repo
      shell: bash
      run: |
        echo "TODO: Implement environment repo update logic"
        echo "Application: ${{ inputs.application }}"
        echo "Version: ${{ inputs.version }}"
