name: "aws-push-docker-image"
description: Builds a Docker image from a .Dockerfile and pushes it to AWS ECR

inputs:
  container-name:
    description: The name of the Docker container
    required: false
    default: ${{ github.event.repository.name }}

  software-version:
    description: The tag version of the image
    required: false
    default: latest

  aws-role-arn:
    description: ARN of the IAM role to assume via OIDC
    required: true

  aws-region:
    description: AWS region for ECR
    required: false
    default: eu-west-1

  additional-path:
    description: Path prefix if Dockerfile is not in root (e.g. `/grafana/`)
    required: false
    default: ""

  dotnet-version:
    description: Optional .NET version to install before build
    required: false
    default: "9.x"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      shell: bash
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ inputs.container-name }}:${{ inputs.software-version }} \
          workflow/repository/${{ inputs.additional-path }}

    - name: Push to ECR
      shell: bash
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.container-name }}:${{ inputs.software-version }}
