name: 'Dotnet Pack and Publish'
description: 'Packs and publishes .NET NuGet packages to a specified package source'
author: 'Ignitia'

inputs:
  nuget-api-key:
    description: 'API key for the NuGet package source.'
    required: true
  package-path:
    description: 'Path to the folder containing .csproj files to package'
    required: true
  package-source:
    description: 'NuGet package source name'
    required: true
  package-version:
    description: 'Version to assign to the packages'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install xmllint
      shell: bash
      run: |
        if command -v apt-get &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y libxml2-utils
        elif command -v yum &> /dev/null; then
          sudo yum install -y libxml2
        fi
    - name: Build, pack, and publish .csproj files
      shell: bash
      working-directory: ${{ inputs.package-path }}
      run: |
        shopt -s globstar
        for file in **/*.csproj; do
          IS_PACKABLE=$(xmllint --xpath "string(//IsPackable)" "$file" 2>/dev/null)
          echo "File: $file | IsPackable: '$IS_PACKABLE'"
          if [ "$IS_PACKABLE" != "false" ]; then
            echo "Processing $file"
            dotnet pack "$file" -p:PackageVersion=${{ inputs.package-version }} -c Release --output .
            PACKAGE_NAME="$(basename "${file%.*}").${{ inputs.package-version }}.nupkg"
            dotnet nuget push "$PACKAGE_NAME" \
              --api-key "${{ inputs.nuget-api-key }}" \
              --source "${{ inputs.package-source }}" \
              --skip-duplicate
          else
            echo "Skipping $file as IsPackable is set to false"
          fi
        done